CREATE TABLE `itemauction` (
  `ia_id` INT(11) UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT ,
  `ia_adder` INT(11) UNSIGNED NOT NULL ,
  `ia_item` INT(11) UNSIGNED NOT NULL ,
  `ia_qty` INT(11) UNSIGNED NOT NULL ,
  `ia_end` INT(11) UNSIGNED NOT NULL ,
  `ia_bidder` INT(11) UNSIGNED NOT NULL ,
  `ia_bid` BIGINT(11) UNSIGNED NOT NULL ,
  UNIQUE (`ia_id`)) ENGINE = MyISAM;