CREATE TABLE `jobs` (
  `jRANK` INT(11) UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT ,
  `jNAME` TEXT NOT NULL ,
  `jSTART` INT(11) UNSIGNED NOT NULL ,
  `jDESC` TEXT NOT NULL ,
  `jBOSS` INT NOT NULL ,
  UNIQUE (`jRANK`)
) ENGINE = MyISAM;

CREATE TABLE `job_ranks` (
  `jrID` INT(11) UNSIGNED NULL DEFAULT NULL AUTO_INCREMENT ,
  `jrJOB` INT(11) UNSIGNED NOT NULL ,
  `jrPRIMPAY` INT(11) UNSIGNED NOT NULL ,
  `jrSECONDARY` INT(11) UNSIGNED NOT NULL ,
  `jrACT` INT(11) UNSIGNED NOT NULL ,
  `jrSTR` INT(11) UNSIGNED NOT NULL ,
  `jrLAB` INT(11) UNSIGNED NOT NULL ,
  `jrIQ` INT(11) UNSIGNED NOT NULL ,
  UNIQUE (`jrID`)
) ENGINE = MyISAM;

ALTER TABLE `job_ranks` ADD `jrRANK` TEXT NOT NULL AFTER `jrID`;
ALTER TABLE `jobs` CHANGE `jBOSS` `jBOSS` TEXT NOT NULL;